var locations = [{lat: 42.301940, lng: -83.688820},{lat: 31.661013, lng: -106.341509},{lat: -22.408042, lng: -45.788534},{lat: 24.044987, lng: -104.608431},{lat: 23.987092, lng: -104.688514},{lat: -22.1862577, lng: -46.7655597},{lat: 23.171257, lng: -102.882377},{lat: 23.196467, lng: -102.86142},{lat: 25.665086, lng: -100.176687},{lat: 25.468187, lng: -108.107282},{lat: -23.323138, lng: -45.736131},{lat: 27.480565, lng: -99.547174},{lat: 27.446062, lng: -99.501277},{lat: 24.858447, lng: -99.552719},{lat: 28.277387, lng: -105.48504},{lat: 25.775019, lng: -108.986714},{lat: 27.482204, lng: -99.546250},{lat: 31.749426, lng: -106.438141},{lat: 27.445943, lng: -99.501498},{lat: -22.5538239, lng: -45.7690442},{lat: 26.925381, lng: -105.695944},{lat: 31.7429155, lng: -106.4256207},{lat: 31.743350, lng: -106.428883},{lat: 31.708671, lng: -106.420896},{lat: 31.7246002, lng: -106.4005803},{lat: 31.749505, lng: -106.438814},{lat: -23.616711, lng: -46.558420},{lat: 23.739161, lng: -103.993619},{lat: 23.754893, lng: -99.15724},{lat: -99.082841, lng: -99.082841},{lat: 22.75388, lng: -102.505354},{lat: 22.765017, lng: -102.485103}];
var plantas = ['ANN ARBOR CSC', 'COMPLEJO', 'CONCEIÇÃO DOS OUROS', 'DURANGO I', 'DURANGO II', 'ESPÍRITO SANTO DO PINHAL MFG', 'FRESNILLO I', 'FRESNILLO II', 'GUADALUPE III', 'GUAMUCHIL', 'JAMBEIRO MFG', 'LAREDO I', 'LAREDO II', 'LINARES', 'MEOQUI', 'MOCHIS', 'MSB', 'MTC', 'NUEVO LAREDO II ENGINEERING CENTER', 'PARAISOPOLIS MFG', 'PARRAL', 'RBE IV', 'RBE IV - XIII', 'RBE IX', 'RBE V', 'RBE XXI', 'SAO CAETANO OFFICE', 'VICENTE GUERRERO', 'VICTORIA I', 'VICTORIA II', 'ZACATECAS I', 'ZACATECAS II'];
var empleado = [['E003828679','JUAN JOSE CAMACHO FELIX','MFRA. SENIOR II','YES','O','Manufacturing','MOCHIS'],
['E003824714','RIGOBERTO TREJO BERRELLEZA','Manufacturing Support Manager','YES','ME','Manufacturing','DURANGO II'],
['E003828680','FRANCISCO MIGUEL MARISCAL QUINTERO','Sr PE Supervisor - Mfg / Indl','YES','ME','Product Engineering','MOCHIS'],
['E003824717','ESTEBAN GARCES GAYTAN','Operations Supervisor','YES','O','Manufacturing','MEOQUI'],
['E003824718','ERBEY MARTINEZ ESTRADA','ME Supervisor - Mfg / Indl','YES','O','Manufacturing Engineering','MEOQUI'],
['E003824720','HECTOR GUSTAVO SANCHEZ LOYA','Sr Operations General Supervisor','YES','EE','Manufacturing','MEOQUI'],
['E003824722','ALBERTO GUADALUPE LICON RIVERA','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','MEOQUI'],
['E003846807','MARIO ENRIQUE MORALES VILLARREAL','ING SENIOR II','YES','ME','Quality','MSB'],
['E003846808','ARIEL OMAR CABRALES VILLA','ING SENIOR II','YES','EE','Manufacturing Engineering','MSB'],
['E003846811','MAURICIO MARTINEZ CARDENAS','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','LAREDO II'],
['E003833348','RODOLFO REYES DAVILA','FINANZAS CONTRALOR','YES','O','Finance','ZACATECAS II'],
['E003843871','JORGE ARMANDO RODRIGUEZ CARRILLO','Manufacturing Specialist','YES','N/A','Manufacturing','ZACATECAS II'],
['E003833350','EDSON CLODUALDO GONZALEZ DEL REAL','Production Control Manager','YES','EE','Production Control','ZACATECAS II'],
['E003835385','LUZ ELENA TREJO AMARO','Sr Quality Control Gen Supervisor','YES','ME','Quality','FRESNILLO I'],
['E003824726','GUILLERMO SANTANA LEYVA','Sr Manufacturing Operations Engineer','YES','ME','Manufacturing','DURANGO II'],
['E003824727','ELIDA ISABEL SANTILLAN ACOSTA','Sr Quality Control Gen Supervisor','YES','O','Quality','MEOQUI'],
['E003824730','SANDRA TELLEZ PORTILLO','Labor Relations Supervisor','YES','EE','Human Resources','MEOQUI'],
['E003824731','MARIBEL CASTAÑEDA SEGUNDO','Production Control Supervisor','YES','EE','Production Control','MEOQUI'],
['E003811617','ALBERTO POSADA CARDENAS','Sr Manufacturing Operations Engineer','YES','EE','Manufacturing','RBE V'],
['E003839336','RAFAEL NAVARRO ESPINOZA','Gerente Operaciones','YES','ME','Manufacturing','RBE IX'],
['E003824733','ARTURO GARCIA GALVAN','Operations Supervisor','YES','EE','Manufacturing','MEOQUI'],
['E003828688','JUAN ALFREDO TORRES MARTINEZ','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','MOCHIS'],
['E003824734','SILVIA YADIRA CABRERA MOTA','Operations Supervisor','YES','EE','Manufacturing','MEOQUI'],
['E003808862','OCTAVIO ESTRADA GUTIERREZ','SPTTE MANUFACTURA','YES','EE','Manufacturing','RBE IV'],
['E003837144','VICTOR HUGO ROCHA GARCIA','Sr Operations General Supervisor','YES','ME','Manufacturing','FRESNILLO II'],
['E003831668','SERGIO ENRIQUE MENDEZ ARECHIGA','Sr ME Program Mgr','YES','ME','Manufacturing Engineering','DURANGO II'],
['E003837147','FRANCISCO JAVIER GALLEGOS DOMINGUEZ','GERENTE MANTENIMIENTO SENIOR II','YES','ME','Manufacturing','FRESNILLO II'],
['E003831669','WILBERT ALONSO RASCON GRANADOS','Sr HR Operations Supervisor','YES','ME','Human Resources','MEOQUI'],
['E003837150','HECTOR RUBEN LOPEZ ANAYA','GERENTE MANUFACTURA SENIOR II','YES','ME','Manufacturing','FRESNILLO II'],
['E003831674','SILVIA XITLALY PRIETO LUEVANO','Sr Production Control Gen Supervisor','YES','EE','Production Control','RBE IV - XIII'],
['E006204342','Alex Severini','Sales Manager - Toyota','YES','EE','Sales & Marketing','ANN ARBOR CSC'],
['E003839342','FRANCISCO JAVIER GUERRERO PLATAS','MFRA AVANZADO II','YES','EE','Manufacturing','LINARES'],
['E003839344','PEDRO ANTONIO NAVARRO TORRES','MANUFACTURA AVANZADO II','YES','EE','Manufacturing','LINARES'],
['E003839401','CARLOS ALBERTO MOTA MALDONADO','Assoc Operations Supervisor','YES','EE','Manufacturing','VICTORIA II'],
['E003841341','CARLOS EDUARDO SOTELO RUIZ','Manufacturing Support Supervisor','YES','ME','Manufacturing','VICTORIA I'],
['E003841343','DOMINGO BAEZ NUÑEZ','Quality Supervisor','YES','EE','Quality','VICTORIA I'],
['E003839347','COSME MORALES VALDES','MFRA AVANZADO II','YES','EE','Manufacturing','LINARES'],
['E003839348','JESUS ALFONSO ROJAS LOPEZ','GERENTE DE MANUFACTURA','YES','EE','Manufacturing','LINARES'],
['E003846847','LUIS EDUARDO COVARRUBIAS TREVIÑO','Maintenance Supervisor','YES','ME','Manufacturing','LAREDO I'],
['E003843808','VICENTE GUILLEN LEMUS','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','VICTORIA II'],
['E003811620','EFREN RODRIGUEZ GARCIA','SENIOR DE CAL II','YES','EE','Quality','RBE XXI'],
['E003849922','CYNTHIA ELIZABETH LOPEZ DUEÑAS','Ingeniero Senior de Calidad III','YES','EE','Quality','GUADALUPE III'],
['E003846851','ADA ILIZALITURRI VERASTEGUI','Sr Accountant','YES','EE','Finance','LAREDO II'],
['E003841348','RUTILO MALAGA CAPI','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','VICTORIA I'],
['E003833356','JULIO CESAR ORTIZ GARCIA','Senior ME Engineer - Mfg / Indl','YES','ME','Manufacturing Engineering','FRESNILLO I'],
['E003843812','SERGIO ARTURO TRUJILLO CANTU','RH SENIOR II','YES','ME','Human Resources','LAREDO II'],
['E003846866','JOSE DANIEL HERNANDEZ HERNANDEZ','Sr Operations General Supervisor','YES','O','Manufacturing','LAREDO I'],
['E003910223','MIGUEL ANGEL JAUREGUI CHAVEZ','Labor Relations Supervisor','YES','ME','Human Resources','LAREDO I'],
['E003849926','J JOHEL FLORES RODRIGUEZ','RH SENIOR II','YES','ME','Human Resources','LAREDO I'],
['E003846874','CESAR ANDRADE ACOSTA','MANUFACTURA AVANZADO III','YES','EE','Manufacturing','LAREDO II'],
['E003845254','ROBERTO CASTILLO LOPEZ','Quality Control Engineer','YES','ME','Quality','LAREDO I'],
['E003846892','JUAN CARLOS GONZALEZ RODRIGUEZ','Production Control Supervisor','YES','ME','Production Control','LAREDO I'],
['E003841353','ENRIQUE XICOTENCATL SOTELO GONZALEZ','INGENIERO AVANZADO II','YES','ME','Manufacturing Engineering','VICTORIA I'],
['E003849930','RUBEN ALFONSO RODRIGUEZ MARTINEZ','Sr Operations General Supervisor','YES','ME','Manufacturing','GUADALUPE III'],
['E003839359','ARTURO NUÑEZ DE LA CRUZ','MFRA AVANZADO II','YES','EE','Manufacturing','LINARES'],
['E003833357','FRANCISCO JAVIER AGUILAR ARTEAGA','GERENTE DE PLANTA','YES','ME','Manufacturing','ZACATECAS II'],
['E003849939','HECTOR TAMEZ CORONADO','Senior ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','GUADALUPE III'],
['E003811621','NACHELI DONAJI REYES DE LA GARZA (On Leave)','Manager of the FORD/FCA/EU Programs Mgrs','YES','EE','Advanced Engineering','RBE XXI'],
['E003839361','HECTOR GARZA PEREZ','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','LAREDO II'],
['E003849942','ROSALINDA RODRIGUEZ REYES','Ingeniero Senior II','YES','EE','Manufacturing Engineering','GUADALUPE III'],
['E003849945','EDUARDO APOLINAR GARCIA SILVA','GERENTE DE INGENIERIA INDUSTRIAL','YES','ME','Manufacturing Engineering','LINARES'],
['E003849951','ROBERTO GONZALEZ CAMPOS','Ingeniero Senior I','YES','EE','Manufacturing Engineering','GUADALUPE III'],
['E003843817','LUIS DAVID HERNANDEZ JUAREZ','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','VICTORIA I'],
['E003839369','LUIS ALONSO GONZALEZ MARTINEZ','Senior ME Manager - Mfg / Indl','YES','ME','Manufacturing Engineering','VICTORIA II'],
['E003820880','MAXIMILIANO ALMANZA SANDOVAL','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','MEOQUI'],
['E003820881','SERGIO RAMON CAUDILLO LOZOYA','ME Supervisor - Mfg / Indl','YES','O','Manufacturing Engineering','MEOQUI'],
['E003811622','CARLOS LOPEZ ESPINOZA','CAL AVANZADO III','YES','O','Quality','RBE XXI'],
['E008700030','Frank Szuba','Chief Engineer - Silicon Valley','YES','N/A','Product Engineering','MTC'],
['E008700783','Dawn Wheeler','GM Sales Admin/BOM Manager','YES','N/A','Product Engineering','MTC'],
['E008700866','Carlos Perez','Purchasing Manager','YES','N/A','Supply Chain Management','MTC'],
['E008701538','Kenneth Rivera','Manager, GM Program Management','YES','N/A','Product Engineering','MTC'],
['E003811626','ELSA ARACELI PEREZ MARTIN DEL CAMPO','MANAGER DE COMP I','YES','EE','Supply Chain Management','RBE XXI'],
['E003807937','ROSA LIDIA PAUL GAYTAN','Sr Operations General Supervisor','YES','EE','Manufacturing','RBE V'],
['E003803578','JOSE SABAS GOMEZ MACHADO','Sr Operations General Supervisor','YES','EE','Manufacturing','RBE IX'],
['E003800854','ENRIQUE PEREZ RODRIGUEZ','ING. AVANZADO III','YES','ME','Manufacturing Engineering','RBE IV - XIII'],
['E003805755','COSME DAMIAN ORTA LOPEZ','Manufacturing Operations Engineer','YES','EE','Manufacturing','RBE V'],
['E003803579','RUTH MERCEDES RAMIREZ MARTINEZ','Production Control Supervisor','YES','EE','Production Control','RBE IV'],
['E003805756','MARTHA ANGELICA MEDINA ARANDA','Mtls & PC Scheduler','YES','EE','Production Control','RBE V'],
['E003805757','LUIS ALBERTO REZA RODRIGUEZ','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','RBE V'],
['E003811636','JUANA JOSEFA GUERRERO FLORES','ING. SENIOR III','YES','O','Manufacturing Engineering','RBE XXI'],
['E003800866','MANUEL HECTOR VAZQUEZ BORDAS','Sr ME Supervisor - Systems','YES','ME','Manufacturing Engineering','RBE IV - XIII'],
['E000151550','MIGUEL ANGEL MARTINEZ PEREZ','PLANT MANAGER','YES','N/A','Manufacturing Engineering','COMPLEJO'],
['E000151550','MIGUEL ANGEL MARTINEZ PEREZ','PLANT MANAGER','YES','N/A','Manufacturing Engineering','COMPLEJO'],
['E000151550','MIGUEL ANGEL MARTINEZ PEREZ','PLANT MANAGER','YES','N/A','Manufacturing Engineering','COMPLEJO'],
['E000223481','BLANCA VERONICA LUJAN CAMPOS','Sr HR Operations Supervisor','YES','N/A','Human Resources','COMPLEJO'],
['E000223481','BLANCA VERONICA LUJAN CAMPOS','Sr HR Operations Supervisor','YES','N/A','Human Resources','COMPLEJO'],
['E000223481','BLANCA VERONICA LUJAN CAMPOS','Sr HR Operations Supervisor','YES','N/A','Human Resources','COMPLEJO'],
['E003811641','ARMANDO CARRASCO JURADO','ING. SENIOR III','YES','EE','Manufacturing Engineering','RBE XXI'],
['E003811652','JUAN ALFREDO AGUERO FLORES','GERENTE JUNIOR','YES','ME','Quality','COMPLEJO'],
['E003811652','JUAN ALFREDO AGUERO FLORES','GERENTE JUNIOR','YES','ME','Quality','COMPLEJO'],
['E003811652','JUAN ALFREDO AGUERO FLORES','GERENTE JUNIOR','YES','ME','Quality','COMPLEJO'],
['E003807942','RAYMUNDO AGUERO CALDERA','MANUFAC AVANZADO III','YES','ME','Manufacturing','RBE V'],
['E003800871','ROGELIO HINOJO GALLEGOS','SENIOR I','YES','ME','Quality','COMPLEJO'],
['E003800871','ROGELIO HINOJO GALLEGOS','SENIOR I','YES','ME','Quality','COMPLEJO'],
['E003800871','ROGELIO HINOJO GALLEGOS','SENIOR I','YES','ME','Quality','COMPLEJO'],
['E003805761','MAYRA YADIRA BUSTILLOS SUJO','Training Supervisor','YES','EE','Human Resources','RBE V'],
['E003803588','RUBEN ALEJANDRO PEREZ MONTALVO','SUP.GENERAL','YES','EE','Production Control','RBE IX'],
['E003803589','IRVING SALAZAR SALAZAR','PC&L SENIOR I','YES','EE','Production Control','RBE IV'],
['E003803590','JORGE RODRIGUEZ TORRES','Customer Satisfaction Supervisor','YES','ME','Quality','RBE IV'],
['E003803592','RAUL SERRATO HERNANDEZ','Sr Quality Gen Supervisor','YES','ME','Quality','RBE IV'],
['E003801701','ALFREDO ADRIAN ROCILLO GARCIA','Manufacturing Support Supervisor','YES','ME','Manufacturing','RBE IV'],
['E003803980','ROBERTO HERNANDEZ LOMELI','Manufacturing Operations Engineer','YES','ME','Manufacturing','DURANGO II'],
['E003805774','JUAN PABLO RETE MEZA','Manufacturing Operations Engineer','YES','EE','Manufacturing','RBE V'],
['E003807943','GUILLERMO QUIÑONEZ OLIVAS','Sr Production Control Gen Supervisor','YES','EE','Production Control','RBE IX'],
['E003804823','JUAN CARLOS REYES MELCHOR','Mtls & PC Scheduler','YES','EE','Production Control','RBE IX'],
['E003935493','ALBERTO RODRIGUEZ VALDES','Sr Customer Satisfaction Gen Supervisor','YES','ME','Quality','LAREDO I'],
['E003803596','HUGO ALFONSO BRACHO PIMENTEL','MANAGER MANUFACT.II','YES','EE','Manufacturing','RBE IV'],
['E003800874','RAMON RICO RETANA','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','DURANGO II'],
['E003800875','JUAN MANUEL VERDUGO MOROYOQUI','ING. AVANZADO III','YES','O','Manufacturing Engineering','COMPLEJO'],
['E003800875','JUAN MANUEL VERDUGO MOROYOQUI','ING. AVANZADO III','YES','O','Manufacturing Engineering','COMPLEJO'],
['E003800875','JUAN MANUEL VERDUGO MOROYOQUI','ING. AVANZADO III','YES','O','Manufacturing Engineering','COMPLEJO'],
['E003811675','MANUEL ROMERO MENDEZ','Sr Quality Control Gen Supervisor','YES','ME','Quality','RBE XXI'],
['E003807949','YILIN EVANGELINA GONZALEZ RAMIREZ','Production Control Supervisor','YES','EE','Production Control','RBE IX'],
['E003803600','JOSE DE LA LUZ HINOJOS MONTOYA','MFRA SENIOR II','YES','ME','Manufacturing','RBE IV'],
['E003808877','RICARDO VALENZUELA LIZARRAGA','Asst ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003808877','RICARDO VALENZUELA LIZARRAGA','Asst ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003808877','RICARDO VALENZUELA LIZARRAGA','Asst ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003807952','HECTOR JUAN REYNA VAZQUEZ','Quality Supervisor','YES','EE','Quality','RBE IX'],
['E003800799','SAUL DORADO FERNANDEZ','Operations Supervisor','YES','EE','Manufacturing','RBE IX'],
['E003800803','DAVID RAMOS MELENDEZ','Supervisor Avanzado','YES','O','Manufacturing Engineering','RBE V'],
['E003806814','ROGELIO MOLINA TORRES','Manufacturing Coordinator','YES','EE','Manufacturing','RBE IX'],
['E003807055','CARLOS LEGASPY CHAVEZ','Production Control Coordinator','YES','EE','Production Control','RBE IX'],
['E003808879','SERGIO ALBERTO HERNANDEZ ROMERO','Supervisor de Ingenieria','YES','ME','Manufacturing Engineering','RBE V'],
['E000035179','ALEJANDRO IBARRA VARELA','HR Generalist','YES','EE','Human Resources','RBE XXI'],
['E000211451','ELIA MARINA IBARRA ORTIZ','HR Supervisor','YES','N/A','Human Resources','RBE IX'],
['E003805788','NOE TORRES MUÑOZ','ING. AVANZADO II','YES','EE','Manufacturing Engineering','PARRAL'],
['E003818660','JOSE LUIS CAMPUZANO TALAMANTES','SUP. MANTENIMIENTO','YES','EE','Manufacturing','PARRAL'],
['E003811696','JOSE SAMUEL RUIZ OLIVAS','DIRECTOR REGIONAL','YES','ME','Manufacturing','RBE IV - XIII'],
['E003818661','LUIS CARLOS RAMOS JIMENEZ','PC&L AVANZADO I','YES','EE','Production Control','MEOQUI'],
['E003818663','DAMASO CARLOS POLANCO DE LA O','Northwest Operations Director','YES','EE','Manufacturing','MEOQUI'],
['E003818665','EDUARDO NUÑEZ BARRAZA','INGENIERO SENIOR I','YES','ME','Manufacturing Engineering','PARRAL'],
['E003816769','KARLA SIOMARA ALDAZ MARQUEZ','Labor Relations Supervisor','YES','EE','Human Resources','PARRAL'],
['E003818667','KARINA JULIETA GONZALEZ DOMINGUEZ','Servicio al Cliente/Programacion','YES','EE','Production Control','PARRAL'],
['E003841360','LUIS RAUL MORENO BACA (On Leave)','Quality Engineering Manager','YES','ME','Quality','MEOQUI'],
['E003805637','ROBERTO PARDO SANDOVAL','MFG SENIOR I','YES','ME','Manufacturing','RBE IV'],
['E003808726','RICARDO CARMONA LOZANO','Senior PE Engineer - Electrical','YES','ME','Product Engineering','RBE V'],
['E003808728','JAVIER PARRAS SANCHEZ','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808728','JAVIER PARRAS SANCHEZ','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808728','JAVIER PARRAS SANCHEZ','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003803603','GUILLERMO MORENO SALCIDO','Sr Operations General Supervisor','YES','EE','Manufacturing','RBE V'],
['E003805646','CESAR DAVID SOLARES CAZARES','Production Control Supervisor','YES','ME','Production Control','RBE V'],
['E003811703','MISAEL ALEJANDRO GONZALEZ CONTRERAS','PRODUCT ENGINEERING','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003811703','MISAEL ALEJANDRO GONZALEZ CONTRERAS','PRODUCT ENGINEERING','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003811703','MISAEL ALEJANDRO GONZALEZ CONTRERAS','PRODUCT ENGINEERING','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003808401','RICARDO REYES SAUCEDO','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808401','RICARDO REYES SAUCEDO','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808401','RICARDO REYES SAUCEDO','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808837','VICTOR EMMANUEL VERGARA GARCIA','ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','RBE V'],
['E003808539','ESTEFANIA LECHUGA MUÑOZ (On Leave)','INGENIERO DE PE ASOC-MATL/QUIM','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808539','ESTEFANIA LECHUGA MUÑOZ (On Leave)','INGENIERO DE PE ASOC-MATL/QUIM','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E003808539','ESTEFANIA LECHUGA MUÑOZ (On Leave)','INGENIERO DE PE ASOC-MATL/QUIM','YES','ME','Manufacturing Engineering','COMPLEJO'],
['E000003171','MARIA OLIVIA FIERRO PEREZ','Senior ME Manager - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E000003171','MARIA OLIVIA FIERRO PEREZ','Senior ME Manager - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E000003171','MARIA OLIVIA FIERRO PEREZ','Senior ME Manager - Mfg / Indl','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003844958','ARTURO CONTRERAS CISNEROS','Sr Supplier Quality Engineer','YES','EE','Supply Chain Management','ZACATECAS II'],
['E003803605','RUBEN ALEJANDRO MENDOZA RIOS','MANAGER DE MFG I','YES','EE','Manufacturing','RBE IV'],
['E003803417','ANA CARMINA CERVANTES CHAVEZ','SUP. LABORALES','YES','EE','Human Resources','RBE IV'],
['E003803445','ERIC PAVON CORTES','MFG SUPERVISOR','YES','EE','Manufacturing','RBE IV'],
['E003828691','JOSE ANGEL ZARATE ESPINOZA','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','MOCHIS'],
['E003800891','RIGOBERTO MENA SALAZAR','ING SENIOR CAL III','YES','ME','Quality','VICTORIA II'],
['E003831686','ALEJANDRO CHAVIRA ALVAREZ','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','DURANGO I'],
['E003807960','RICARDO RENTERIA DOMINGUEZ','MANAGER MFG I','YES','ME','Manufacturing','RBE V'],
['E003811720','VICTOR MANUEL REYES HERMOSILLO','ING. SENIOR III','YES','EE','Manufacturing Engineering','RBE XXI'],
['E003831689','DENICE ACOSTA BOJORQUEZ','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','MOCHIS'],
['E003800895','ISMAEL RODRIGUEZ DOMINGUEZ','PE Engineer - Electrical','YES','O','Product Engineering','MTC'],
['E003808889','HECTOR CARBALLO RIVERA','ME Supervisor - Electrical','YES','EE','Manufacturing Engineering','RBE IV - XIII'],
['E000151996','ANA ELENA FLORES ARMENDARIZ','HR Manager','YES','ME','Human Resources','RBE IV - XIII'],
['E003811765','SAUL ALBERTO GARCIA SOTO','CAL AVANZADO I','YES','ME','Quality','RBE XXI'],
['E003811777','JORGE ALBERTO MORENO ANAYA','Programador de Mat y PC&L','YES','ME','Production Control','RBE V'],
['E003811594','OCTAVIO ALBERTO QUINTANA BADILLO','CAL JUNIOR III','YES','ME','Quality','RBE XXI'],
['E003811785','CESAR IBAN GONZALEZ CHAVEZ','ING. SENIOR III','YES','EE','Manufacturing Engineering','RBE XXI'],
['E000034148','FRANCISCO JAVIER ROSAS MARTINEZ','Product Engineering - Program Management Supervisor','YES','EE','Product Engineering','RBE XXI'],
['E000079366','ALEJANDRO ARTURO SOLANO NEVAREZ','Sr ME Program Mgr','YES','ME','Manufacturing Engineering','PARRAL'],
['E000201240','JORGE RICARDO CASTILLO TREVIÑO','Accounting Manager','YES','N/A','Finance','RBE XXI'],
['E006206070','Carlos Eugenio de Sa Freire Junior','Finance Director, EDS Mexico','YES','N/A','Finance','RBE XXI'],
['E003811789','LUZ IRENE TORRES TORRES','Plant Controller','YES','ME','Finance','RBE XXI'],
['E003811791','HERMINIA ARACELY RAMIREZ ALCANTARA','Sr Product Engineering - Program Management Supervisor','YES','ME','Product Engineering','RBE XXI'],
['E003820890','CARLOS ALBERTO ARREOLA MARTINEZ','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','DURANGO I'],
['E003812646','RODOLFO CASTRO LOPEZ','ME Manager - Electrical','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003812646','RODOLFO CASTRO LOPEZ','ME Manager - Electrical','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003812646','RODOLFO CASTRO LOPEZ','ME Manager - Electrical','YES','EE','Manufacturing Engineering','COMPLEJO'],
['E003808747','LEONARDO JOEL BURBOA VALENZUELA','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','RBE IV - XIII'],
['E003812713','JOSE LUIS RANGEL GONZALEZ','Sr PE Supervisor - Electrical','YES','O','Product Engineering','COMPLEJO'],
['E003812713','JOSE LUIS RANGEL GONZALEZ','Sr PE Supervisor - Electrical','YES','O','Product Engineering','COMPLEJO'],
['E003812713','JOSE LUIS RANGEL GONZALEZ','Sr PE Supervisor - Electrical','YES','O','Product Engineering','COMPLEJO'],
['E003811813','GERARDO ISMAEL REYES MACIAS','COMP SENIOR III','YES','EE','Supply Chain Management','RBE XXI'],
['E003811814','RUBEN CHAVEZ OCHOA','Sr Purchasing Supervisor','YES','EE','Supply Chain Management','RBE XXI'],
['E000212200','EDUARDO TELLEZ MARTINEZ','Sr Accounting Consultant','YES','N/A','Finance','ZACATECAS II'],
['E000010090','ALEXIA DANIELA MEJIA LOZOYA','Sup. de Pesonal Avanzado','YES','O','Human Resources','GUAMUCHIL'],
['E003818671','OSCAR YAZIR HERNANDEZ TORRES','MFA SENIOR II','YES','ME','Manufacturing','PARRAL'],
['E003818672','JUAN GABRIEL RODRIGUEZ ANAYA','SENIOR CALIDAD','YES','EE','Quality','PARRAL'],
['E003818673','ADRIAN ALBERTO CARRIEDO VILLALOBOS','PC&L SENIOR','YES','EE','Production Control','PARRAL'],
['E003843883','JOSE ABRAHAM ALVAREZ HERNANDEZ','Manufacturing Operations Engineer','YES','EE','Manufacturing','DURANGO II'],
['E003818677','LEONARDO JAVIER DEL BOSQUE BACA','ING. PROCESO SENIOR I','YES','EE','Manufacturing Engineering','PARRAL'],
['E003817833','BERTHA ALICIA CHAVEZ LOYA','SUP. CAL. AVANZADO','YES','EE','Quality','PARRAL'],
['E003818538','YEDID PATRICIA BALTIERRA GOMEZ','SUP.AVANZADO FINANZAS','YES','O','Finance','RBE XXI'],
['E003831692','ERICKA PATRICIA BETANCOURT MEDINA','Operations Supervisor','YES','ME','Manufacturing','DURANGO I'],
['E003820896','JOEL ARVIZO HUITRON','Sr Production Control Gen Supervisor','YES','ME','Production Control','DURANGO II'],
['E003819085','LUIS IGNACIO RAMIREZ GARCIA','Manufacturing Specialist','YES','ME','Manufacturing','RBE V'],
['E003820897','LUIS MARCOS GONZALEZ MORALES','HR Director, Mexico','YES','EE','Human Resources','RBE XXI'],
['E003833359','OSCAR MARQUEZ LIZALDE','MANAGER','YES','EE','Manufacturing','ZACATECAS I'],
['E003820903','ELISEO FALCON FIERRO','Supervisor General de Operaciones Senior','YES','EE','Manufacturing','VICENTE GUERRERO'],
['E003820907','GILBERTO CALAHORRA LOPEZ','ME Engineer - Mfg / Indl','YES','ME','Manufacturing Engineering','MEOQUI'],
['E003811819','TANYA SOLEDAD LOPEZ SOLIS','Production Control Manager','YES','EE','Production Control','RBE XXI'],
['E003828805','SUSANA LOYA PRIETO','HR Supervisor','YES','EE','Human Resources','RBE XXI'],
['E000223359','RUFINO ARELLANO IBARRA','Sr Accountant','YES','N/A','Finance','DURANGO II'],
['E003824740','BERNARDO PAYAN RENTERIA','Quality Control Supervisor','YES','O','Quality','MEOQUI'],
['E003824742','JUAN MARIO ARTEAGA CERECERES','Operations Supervisor','YES','EE','Manufacturing','MEOQUI'],
['E003824743','GUSTAVO IRIGOYEN OLIVAS','MFA SENIOR III','YES','O','Manufacturing','MEOQUI'],
['E003831704','CARLOS ALBERTO PRIETO CHAVEZ','MFA SENIOR III','YES','EE','Manufacturing','DURANGO I'],
['E003805804','JAIME RASCON RAMOS','ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','MEOQUI'],
['E003824744','CESAR CARRILLO VILLA','Sr Operations General Supervisor','YES','O','Manufacturing','MEOQUI'],
['E000222827','RENE CARMONA PARRA','GERENTE PLANTA','YES','N/A','Manufacturing','PARRAL'],
['E003820918','JUAN MIGUEL LIMONES CABALLERO','Production Control Supervisor','YES','O','Production Control','COMPLEJO'],
['E003820918','JUAN MIGUEL LIMONES CABALLERO','Production Control Supervisor','YES','O','Production Control','COMPLEJO'],
['E003820918','JUAN MIGUEL LIMONES CABALLERO','Production Control Supervisor','YES','O','Production Control','COMPLEJO'],
['E003824751','FAUSTO ARMANDO ESPEJO MUÑOZ','Sr Operations General Supervisor','YES','O','Manufacturing','MEOQUI'],
['E003822135','MARGARITA RODRIGUEZ GONZALEZ','Mfg Maintenance Supervisor','YES','ME','Manufacturing','MEOQUI'],
['E003824754','JAVIER MARMOLEJO ACOSTA','Mtls & PC Scheduler','YES','EE','Production Control','DURANGO II'],
['E003824756','VICTOR MANUEL GONZALEZ VALENZUELA','Operations Supervisor','YES','O','Manufacturing','MEOQUI'],
['E003822275','OSCAR OCTAVIO MARTA DAVILA','Supervisor de Manufactura','YES','O','Manufacturing Engineering','ZACATECAS II'],
['E000198672','ANGELA MARIA MALAGA APONTE','Finance Controller','YES','N/A','Finance','MEOQUI'],
['E003828695','JACOB ISAAC ESPINOZA GAXIOLA','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','DURANGO II'],
['E003828699','LUIS ENRIQUE LEYVA VEA','GERENTE','YES','ME','Production Control','MOCHIS'],
['E003828702','GABRIEL ALBERTO CUADRAS APODACA','SUP SCHEDULING ORDE','YES','O','Production Control','MOCHIS'],
['E003828705','MANUEL HUMBERTO ESPINOZA GAXIOLA','Operations Supervisor','YES','O','Manufacturing','MOCHIS'],
['E003828708','MIGUEL ANGEL DAUTT SANCHEZ','Sr ME Program Mgr','YES','ME','Manufacturing Engineering','MOCHIS'],
['E003831710','SAUL FABRICIO TORRES MARTINEZ','Operations Supervisor','YES','EE','Manufacturing','DURANGO I'],
['E003828710','LUIS ALFONSO SOTO ANGULO','SUPERVISOR COORDI','YES','EE','Manufacturing','MOCHIS'],
['E003800904','GASPAR VEGA OCHOA','Senior ME Engineer - Mfg / Indl','YES','ME','Manufacturing Engineering','RBE V'],
['E003825785','HECTOR ABRAHAM LARA VALENZUELA','SUP. DE MFRA.','YES','O','Manufacturing','GUAMUCHIL'],
['E003828820','OSCAR HERNANDEZ CARREON','Operations Supervisor','YES','EE','Manufacturing','DURANGO I'],
['E003825916','GUILLERMO MAYORGA BOJORQUEZ','Manufacturing Operations Engineer','YES','EE','Manufacturing','MOCHIS'],
['E003828716','JOSE HUMBERTO FIERRO CALDERON','Sup. Avanzado de Ordering','YES','EE','Production Control','MOCHIS'],
['E003824758','OSCAR JAVIER RODRIGUEZ ARMENTA','Mfra. Senior III','YES','O','Manufacturing','GUAMUCHIL'],
['E003922426','JORGE HUMBERTO ANGULO AGRAMON','Supervisor de PC&L','YES','O','Production Control','GUAMUCHIL'],
['E003828839','NAHUM SINOE ANTUNA MENA','Manufacturing Specialist','YES','EE','Manufacturing','DURANGO I'],
['E003829021','JOSE MARIA VILLARREAL RAMIREZ','Operations Supervisor','YES','EE','Manufacturing','DURANGO I'],
['E003824759','CARMEN ALICIA LOPEZ ZAZUETA','Sr Operations General Supervisor','YES','EE','Manufacturing','MEOQUI'],
['E003829319','MARIA FERNANDA MENDEZ FIERRO','Assoc ME Technical Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','DURANGO II'],
['E000195984','OSCAR GUILLERMO MARRUFO VAZQUEZ','Assoc Mtrls & PC Scheduler','YES','N/A','Production Control','DURANGO I'],
['E003829695','YARED FRANCO VALLES','Assoc Quality Engineer','YES','ME','Quality','DURANGO I'],
['E003830681','SERGIO VARGAS DOMINGUEZ','HR Operations Coordinator','YES','ME','Human Resources','DURANGO I'],
['E000037933','OSCAR FERNANDEZ SALAZAR (On Leave)','Assoc ME Technical Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','DURANGO II'],
['E000049794','MATTHEW  GEORGE NG','Sr Quality Gen Supervisor','YES','ME','Quality','DURANGO II'],
['E003844965','LUIS ALBERTO SERVIN VAZQUEZ','Superintendente de Ingenieria Cluster Zacatecas','YES','EE','Manufacturing Engineering','ZACATECAS II'],
['E003833360','ALEJANDRA OLVERA CASTILLO','Sr ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','ZACATECAS I'],
['E003833361','TANIA YAZMIN PEREZ RUELAS','Labor Relations Supervisor','YES','ME','Human Resources','ZACATECAS II'],
['E003833366','JAVIER ALFONSO GARZA REYES','Senior ME Engineer - Mfg / Indl','YES','EE','Manufacturing Engineering','ZACATECAS I'],
['E003833367','GENARO ORTEGA GAMEZ','GERENTE DE CALIDAD','YES','EE','Quality','ZACATECAS II'],
['E003833370','EDUARDO ZORRILLA DAVILA','Production Control Supervisor','YES','EE','Production Control','ZACATECAS II'],
['E003832152','MANUEL DE ALBA BUENROSTRO','Sr Labor Relations Supervisor','YES','ME','Human Resources','ZACATECAS I'],
['E003832188','JORGE LUIS ORTIZ GONZALEZ','Manufacturing Support Supervisor','YES','EE','Manufacturing','ZACATECAS II'],
['E003833376','OSCAR DURAN DE LA ROSA','Quality Control Engineer','YES','ME','Quality','ZACATECAS I'],
['E003833378','JOSE ANTONIO GAMEZ HERNANDEZ','Sr Operations General Supervisor','YES','ME','Manufacturing','ZACATECAS I'],
['E003832660','CHRISTIAN ALEJANDRO DIAZ GUTIERREZ','Production Control Supervisor','YES','EE','Production Control','ZACATECAS II'],
['E003844144','DANIEL FERNANDEZ VAZQUEZ','Manufactura Avanzado II','YES','ME','Manufacturing','GUADALUPE III'],
['E000233566','MILTON CARLOS GONZALEZ DEL REAL','Supervisor de Manufactura','YES','N/A','Production Control','ZACATECAS II'],
['E003844231','JUAN MANUEL DAVILA JIMENEZ','Sr Customer Satisfaction Gen Supervisor','YES','ME','Quality','LAREDO II'],
['E003844272','HERIBERTO RODRIGUEZ MARTINEZ','SUPERVISOR ING. PROCESO','YES','ME','Manufacturing Engineering','ZACATECAS II'],
['E003922894','CLAUDIA FERNANDA SOLANO HUERTA','Assoc Mtrls & PC Scheduler','YES','ME','Production Control','ZACATECAS I'],
['E000017146','MIGUEL FERNANDO AGUILAR FERNANDEZ','Finance Analyst','YES','EE','Finance','RBE XXI'],
['E000028606','ANA KAREN AGUERO SALAS','Assoc Mtrls & PC Scheduler','YES','ME','Production Control','ZACATECAS I'],
['E000116329','BOGAR PABLO FERNANDEZ BAEZ','Assoc HR Generalist','YES','ME','Human Resources','ZACATECAS I'],
['E000225086','CECILIA SIERRA ALVARADO','Assoc Quality Engineering Supervisor','YES','N/A','Quality','FRESNILLO II'],
['E003833636','JASON HINOJOSA GARCIA','Customer Satisfaction Analyst','YES','ME','Quality','FRESNILLO II'],
['E003920155','ERIK MAURICIO GOMEZ CORREA','Manufacturing Coordinator','YES','ME','Manufacturing','FRESNILLO I'],
['E000015621','JUAN CARLOS HOROWICH CASTRO','Manufacturing Coordinator','YES','EE','Manufacturing','FRESNILLO II'],
['E003835398','RICARDO ADOLFO SERNA GALLEGOS','Manufacturing Support Supervisor','YES','EE','Manufacturing','FRESNILLO I'],
['E003837161','FRANCISCA MONARREZ VARGAS','Sr Operations General Supervisor','YES','EE','Manufacturing','FRESNILLO II'],
['E003844980','JOSE HUGO CASTAÑEDA RODARTE','CONT SENIOR III','YES','ME','Finance','ZACATECAS I'],
['E003835779','LUIS FRANCISCO SANCHEZ AGUILAR','Production Control Supervisor','YES','ME','Production Control','FRESNILLO II'],
['E003844982','FRANCISCO DAVID SANCHEZ CAMACHO','GERENTE DE PLANTA','YES','EE','Manufacturing','LAREDO II'],
['E003844983','HECTOR ALEJANDRO SOLIS RESENDIZ','Tecnico de Manufactura','YES','ME','Manufacturing','ZACATECAS I'],
['E003837164','BRENDA VERONICA MARTINEZ ALMARAZ','Mfg Maintenance Supervisor','YES','EE','Manufacturing','FRESNILLO II'],
['E003837167','ERIK ELIEZER HUERTA DE LA TORRE','ORDERING SME','YES','ME','Production Control','FRESNILLO II'],
['E003834613','LUIS RAUL CELAYA DE LA ROSA','Sr Operations General Supervisor','YES','ME','Manufacturing','LAREDO I'],
['E003837168','FRANCISCO VLADIMIR RAMIREZ CERVANTES','Assoc Quality Control Supervisor','YES','N/A','Quality','FRESNILLO II'],
['E003833381','HECTOR CHAVEZ LIZARRAGA','ME Supervisor - Electrical','YES','EE','Manufacturing Engineering','ZACATECAS I'],
['E003835989','LUIS RODOLFO DE LA ROSA MIER','Manufacturing Specialist','YES','ME','Manufacturing','FRESNILLO II'],
['E003837169','JOSE MANUEL BAUTISTA COBARRUBIAS','Sr Operations General Supervisor','YES','ME','Manufacturing','ZACATECAS II'],
['E003835409','CARLO LOPEZ RODRIGUEZ','Sr Production Control Gen Supervisor','YES','ME','Production Control','FRESNILLO I'],
['E003834800','CESAR RODOLFO ORTIZ CASTAÑEDA','JUNIOR III','YES','ME','Manufacturing','FRESNILLO I'],
['E003836221','OSCAR MENCHACA ESCARCIA','Sr Production Control Gen Supervisor','YES','ME','Production Control','LAREDO I'],
['E003836255','MARIA DEL CARMEN CASTRUITA MENDOZA','Asst Operations Supervisor','YES','N/A','Manufacturing','FRESNILLO II'],
['E003835415','BLANCA MARGARITA LOPEZ SANCHEZ','GERENTE DE MATERIAL','YES','ME','Production Control','ZACATECAS I'],
['E003836489','IRMA GABRIELA HERNANDEZ HERRERA','Production Control Supervisor','YES','EE','Production Control','FRESNILLO I'],
['E003833334','OSCAR ALBERTO NUÑEZ CASTRO','Assoc Quality Engineer','YES','EE','Quality','ZACATECAS II'],
['E003836783','SERGIO ALBERTO JUAREZ GARCIA','Quality Control Engineer','YES','EE','Quality','ZACATECAS II'],
['E003836883','JAIRO GERARDO MEDINA GUTIERREZ','Operations Supervisor','YES','N/A','Manufacturing','FRESNILLO II'],
['E000231006','MIGUEL GUEVARA VILLANUEVA','Sr Operations General Supervisor','YES','N/A','Manufacturing','FRESNILLO II'],
['E003839376','ALEJANDRO MARTINEZ CASTRO','GERENTE DE OPERACIONES','YES','EE','Manufacturing','LINARES'],
['E003839377','ALEJANDRA SANCHEZ GARZA','PC&L AVANZADO I','YES','EE','Production Control','LINARES'],
['E003838770','LAURA CECILIA MEDINA MALDONADO','SUPERVISOR DE CALIDAD','YES','EE','Quality','LINARES'],
['E003840033','CARLOS ALBERTO RODRIGUEZ SALDIVAR','PC L JUNIOR III','YES','ME','Production Control','VICTORIA I'],
['E003843830','PEDRO ANGEL TORRES TREVIÑO','Labor Relations Specialist','YES','ME','Human Resources','VICTORIA I'],
['E003841374','RODRIGO GONZALEZ SORIANO','Operations Manager','YES','EE','Manufacturing','VICTORIA I'],
['E003849960','MAYRA MARGARITA HERNANDEZ DOMINGUEZ','Ingeniero AVANZADO II','YES','O','Manufacturing Engineering','DURANGO II'],
['E003841379','SANDRA LUCIA REYES ARGUELLO','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','VICTORIA I'],
['E003843843','ALEJANDRA ESPARZA ROMERO','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','VICTORIA II'],
['E003843844','MARIA DANIELA RODRIGUEZ SALAZAR','ME Supervisor - Mfg / Indl','YES','EE','Manufacturing Engineering','VICTORIA II'],
['E003841582','VALERIANO GERARDO DE LA GARZA CARDENAS','Assoc Quality Control Engineer','YES','EE','Quality','VICTORIA I'],
['E003841583','JOSE JUAN REYES NIÑO','Assoc Quality Systems Supervisor','YES','EE','Quality','VICTORIA II'],
['E003843845','LUIS GERARDO LEAL RODRIGUEZ','Manufacturing Support Supervisor','YES','EE','Manufacturing','VICTORIA II'],
['E003913775','ALEJANDRA YOCELYN PANTOJA CAVAZOS','Assoc Mtrls & PC Scheduler','YES','ME','Production Control','VICTORIA II'],
['E003840507','EDGAR JAVIER LORES ELIZONDO','Manufacturing Specialist','YES','ME','Manufacturing','LAREDO I'],
['E003840581','LEOVI FERNANDO DE LA FUENTE SAUCEDO','INGENIERO  JUNIOR III','YES','EE','Manufacturing Engineering','VICTORIA I'],
['E003843846','JOSE ENRIQUE WONG ZAPIEN','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','LAREDO II'],
['E003846916','HECTOR IVAN REYES BANDA','ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','LAREDO II'],
['E003843854','KENNY GONZALEZ SEGURA','Manufacturing Support Supervisor','YES','ME','Manufacturing','VICTORIA I'],
['E003842780','ANTONIO PABLO GONZALEZ SANCHEZ','Production Control Coordinator','YES','ME','Production Control','VICTORIA II'],
['E000160702','MARCO ANTONIO SANCHEZ MARTINEZ','Sr Financial Planning & Analysis Supervisor','YES','N/A','Finance','VICTORIA II'],
['E000009449','CARLOS ALBERTO VALDEZ HOLGUIN','Manufactura Avanzado II','YES','ME','Manufacturing','GUADALUPE III'],
['E003837143','JOSE DIEGO ROJAS GARCIA','ME Engineer - Mfg / Indl','YES','O','Manufacturing Engineering','FRESNILLO II'],
['E003925124','ALFREDO CAMPOS GARZA','Quality Control Engineer','YES','ME','Quality','LAREDO I'],
['E000141169','ARTURO SAENZ GUERRA','Manufactura Senior I','YES','EE','Manufacturing','LAREDO II'],
['E003847065','MELISSA MARIBEL ZAMORA AVILA','Operations Supervisor','YES','ME','Manufacturing','LAREDO I'],
['E003844989','JORGE GUILLERMO HEREDIA JARAMILLO','Sr Staff ME Program Mgr','YES','O','Manufacturing Engineering','ZACATECAS II'],
['E000103177','AARON RODRIGUEZ BARCO','Customer Satisfaction Supervisor','YES','ME','Quality','LAREDO II'],
['E003844991','JUAN CARLOS RODRIGUEZ CAMPOS','Sr ME Supervisor - Mfg / Indl','YES','ME','Manufacturing Engineering','GUADALUPE III'],
['E003835419','MANUEL LOPEZ DE LUNA','Quality Control Supervisor','YES','EE','Quality','FRESNILLO I'],
['E003849709','JOSE ANTONIO CORDOVA TORRES','Quality Control Engineer','YES','ME','Quality','LAREDO II'],
['E000072645','ROBERTO BADILLO GUTIERREZ','Assoc Operations Supervisor','YES','ME','Manufacturing','GUADALUPE III'],
['E000077172','JORGE ALBERTO GONZALEZ ALMARAZ','Supervisor de  Manufactura','YES','ME','Manufacturing','GUADALUPE III'],
['E000193152','GUSTAVO ALBERTO SOLIS CASTILLO','RH SENIOR II','YES','N/A','Human Resources','GUADALUPE III'],
['E000225684','JOSE LUIS LEOS SOLIS','Plant Controller','YES','N/A','Finance','GUADALUPE III']];